### ISSUE TITLE
Come up with architecture diagram of how data will be connected

### ISSUE THREAD

**Issue by qjimmy** [NJLprograms/CERN-todo#3]

**Comment by NJLprograms** [comment]
Requirements and Features to implement:
- Login to access individual's todos in progresss
- ADD-TODO option
- DELETE-TODO
- VIEW-COMPLETED-TODOS option

**Comment by NJLprograms** [comment]
https://drive.google.com/file/d/1HFfsFvsa6BZK0gN4sZG2H0Hcaqm9J3qb/view?usp=sharing
